"""empty message

Revision ID: 09e62105865e
Revises: 
Create Date: 2021-08-03 02:05:45.417530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e62105865e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('customer', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('reference', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'amount')
    op.drop_column('sessions', 'reference')
    op.drop_column('sessions', 'description')
    op.drop_column('sessions', 'customer')
    # ### end Alembic commands ###
