"""Added transaction_type column to sessionId

Revision ID: 1c242d1e2481
Revises: bcba69623fde
Create Date: 2021-08-24 23:35:27.426524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c242d1e2481'
down_revision = 'bcba69623fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('transaction_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'transaction_type')
    # ### end Alembic commands ###
