"""Added transaction_type column to sessionId

Revision ID: 20c2cbe9f382
Revises: 5dc95488ade8
Create Date: 2021-08-24 23:49:26.664487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c2cbe9f382'
down_revision = '5dc95488ade8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('transaction_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'transaction_type')
    # ### end Alembic commands ###
