"""Added sessionId to transactions

Revision ID: 35a550a7990c
Revises: 20c2cbe9f382
Create Date: 2021-08-25 00:25:35.123390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a550a7990c'
down_revision = '20c2cbe9f382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'session_id')
    # ### end Alembic commands ###
