"""Added transaction_type column to sessionId

Revision ID: 5dc95488ade8
Revises: 1c242d1e2481
Create Date: 2021-08-24 23:49:07.233466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc95488ade8'
down_revision = '1c242d1e2481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'transaction_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('transaction_type', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
